import pathlib
import unittest


class PageContentTests(unittest.TestCase):
    def test_overview_uses_archive_copy_and_windows_safe_dates(self):
        source = pathlib.Path("pages/1_📊_Overview.py").read_text(encoding="utf-8")

        self.assertIn("get_supabase", source)
        self.assertIn("Roulette Desk", source)
        self.assertIn("Every roulette draw, remembered.", source)
        self.assertIn("collapse_recent_calls", source)
        self.assertIn("Resolved calls", source)
        self.assertIn("Top 10 roulette members", source)
        self.assertIn("Roulette spotlight", source)
        self.assertIn("roulette_member_counts", source)
        self.assertIn("render_avatar_markup", source)
        self.assertIn("avatar_url", source)
        self.assertIn("generasi", source)
        self.assertIn("top_roulette_rows", source)
        self.assertIn("ckt-rank-item", source)
        self.assertIn("Same-day Birthday and Graduation sessions are grouped.", source)
        self.assertNotIn('f"""\n            <div class="ckt-ticket">', source)
        self.assertNotIn('<article class="ckt-surface ckt-stat-card', source)
        self.assertNotIn('st.markdown(render_navbar(', source)
        self.assertNotIn("%-d", source)
        self.assertNotIn("Semua tipe event", source)
        self.assertNotIn("Pemenang belum diumumkan", source)

    def test_timeline_uses_ticket_feed_without_raw_table(self):
        source = pathlib.Path("pages/2_⏳_Timeline.py").read_text(encoding="utf-8")

        self.assertIn("get_supabase", source)
        self.assertIn("Ticket Archive", source)
        self.assertIn("Waiting for roulette", source)
        self.assertIn("single_member_event", source)
        self.assertIn("split_timeline_columns", source)
        self.assertIn("group_timeline_by_month", source)
        self.assertIn("ckt-timeline-columns", source)
        self.assertIn("ckt-member-pair", source)
        self.assertIn("ckt-member-pill", source)
        self.assertIn("ckt-ticket-copy", source)
        self.assertIn('<div class="ckt-surface ckt-ticket-card', source)
        self.assertNotIn("Raw table", source)
        self.assertNotIn("Slot A", source)
        self.assertNotIn("Slot B", source)
        self.assertNotIn("st.dataframe", source)
        self.assertNotIn("render_status_chip(False)", source)
        self.assertNotIn('<article class="ckt-surface ckt-ticket-card', source)
        self.assertNotIn('f"""\n            <div class="ckt-surface ckt-ticket-card', source)
        self.assertNotIn('st.markdown(render_navbar(', source)
        self.assertNotIn("%-d", source)
        self.assertNotIn('label_visibility="collapsed"\n    )', source)

    def test_member_corner_uses_english_copy_and_album_layout(self):
        source = pathlib.Path("pages/3_👤_Member_Corner.py").read_text(encoding="utf-8")

        self.assertIn("get_supabase", source)
        self.assertIn("Event history", source)
        self.assertIn("Select a member card", source)
        self.assertIn("Quick search", source)
        self.assertIn("Total cheki", source)
        self.assertIn("member_id_a", source)
        self.assertIn("member_id_b", source)
        self.assertIn("build_member_archive", source)
        self.assertIn("single_member_event", source)
        self.assertIn("segmented_control", source)
        self.assertIn("ckt-member-browser-grid", source)
        self.assertIn("render_member_modal", source)
        self.assertNotIn("Pilih member", source)
        self.assertNotIn("Riwayat sesi", source)
        self.assertNotIn("birthday events", source)
        self.assertNotIn("Session Album", source)
        self.assertNotIn("Collected event history", source)
        self.assertNotIn("Member dossier", source)
        self.assertNotIn('<article class="ckt-surface ckt-album-card">\n', source)
        self.assertNotIn('st.markdown(render_navbar(', source)
        self.assertNotIn("%-d", source)

    def test_admin_uses_event_presets_and_add_member_tab(self):
        source = pathlib.Path("pages/4_🔐_Admin_Panel.py").read_text(encoding="utf-8")

        self.assertIn("get_supabase", source)
        self.assertIn('table("event_presets")', source)
        self.assertIn('table("members")', source)
        self.assertIn("Add member", source)
        self.assertIn("Save member", source)
        self.assertIn("STATUS_OPTIONS", source)
        self.assertIn("GENERATION_OPTIONS", source)
        self.assertIn("Avatar URL", source)
        self.assertIn("render_member_preview", source)
        self.assertIn("duplicate_member_labels", source)
        self.assertIn("Update member", source)
        self.assertIn("Delete member", source)
        self.assertIn("Confirm delete", source)
        self.assertIn("member_usage_count", source)
        self.assertIn("sync_edit_member_state", source)
        self.assertIn('st.columns(4, gap="large")', source)
        self.assertIn("Preset event catalog", source)
        self.assertIn("Update Roulette Results", source)
        self.assertIn("single_member_event", source)
        self.assertIn("Assign member", source)
        self.assertIn("Assign Slot A", source)
        self.assertIn("1 slot", source)
        self.assertIn("2 slots", source)
        self.assertIn("member_id_a", source)
        self.assertIn("member_id_b", source)
        self.assertIn("slot_mode", source)
        self.assertIn("timedelta", source)
        self.assertIn("duration_minutes", source)
        self.assertIn('col_date, col_start, col_event = st.columns', source)
        self.assertIn("ckt-preset-summary", source)
        self.assertIn("ckt-preset-thumb", source)
        self.assertIn('st.session_state["admin_authenticated"]', source)
        self.assertIn('st.secrets["ADMIN_PASSWORD"]', source)
        self.assertNotIn('number_input("Generation"', source)
        self.assertNotIn('number_input("Edit generation"', source)
        self.assertNotIn('time_input("End time")', source)
        self.assertNotIn("EVENT_PRESETS = [", source)
        self.assertNotIn("PRESET_BANNER_URL_OVERRIDES", source)
        self.assertNotIn("event_name = st.text_input", source)
        self.assertNotIn("event_image_url = st.text_input", source)
        self.assertNotIn("This preset comes from the `event_presets` table.", source)
        self.assertNotIn('<div class="ckt-kicker">Duration</div>', source)
        self.assertNotIn('st.markdown(render_navbar(', source)

if __name__ == "__main__":
    unittest.main()
